[package]
name = "text_to_voice"
version = "1.0.7"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
colored = "3.0.0"
toml = "0.8.20"
serde = { version = "1.0.218", features = ["derive"] }
